on:
  - pull_request
  - push

name: create_and_delete
jobs:
  create_nats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run compose
        run: docker compose -f scripts/docker-compose.yaml up -d
      - name: Install dependencies
        run: make up
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install nats cli
        run: go install github.com/nats-io/natscli/nats@latest
      - name: run nats commands
        run: |
              nats context add local --description "Localhost"
              nats context add nats --server http://localhost:4222 --description "NATS Demo" --select
              nats context ls
              # nats server ls
              nats server ping
              # nats sub cli.demo
      # - name: check endpoint
      #   run: curl http://localhost:8222/jsz
  # test_create_and_delete:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Install dependencies
  #     run: make up
  #   - name: Set up Go
  #     uses: actions/setup-go@v3
  #     with:
  #       go-version: 1.19
  #   - name: Install nats cli
  #     run: go install github.com/nats-io/natscli/nats@latest
  #   - name: run nats commands
  #     run: |
  #           nats context add local --description "Localhost"
  #           nats context add nats --server localhost:4222 --description "NATS Demo" --select
  #           nats context ls
  #           nats server ls
  #           nats server ping
  #           # nats sub cli.demo



    

      # - name: start_jetstream
      #   run: |
      #     chmod a+x ${{ github.workspace }}/.github/workflows/entrypoint.sh
      #     docker cp ${{ github.workspace }}/.github/workflows/entrypoint.sh jetstream:docker-entrypoint.sh
      #     docker restart jetstream

      # - name: Sleep for 30 seconds
      #   uses: whatnick/wait-action@master
      #   with:
      #     time: '30s'
      # - name: http to nats
      #   run: curl http://localhost:8222/jsz

# jobs:
#   set_up_nats:
#     name: set up nats
#     runs-on: ubuntu-latest
#     container:
#       image: nats:latest
#       ports:
#         - 4222:4222
#         - 8222:8222
#       options: --name jetstream
    # steps:
    # - uses: actions/checkout@v3
    # - name: start_jetstream
    #   run: |
    #     chmod a+x ${{ github.workspace }}/.github/workflows/entrypoint.sh
    #     docker cp ${{ github.workspace }}/.github/workflows/entrypoint.sh jetstream:/usr/local/bin/docker-entrypoint.sh
    #     docker restart jetstream

    #      - name: start jetstream
    #        run: /usr/local/bin/nats-server --js
  # start_nats_instance:
  #   #  runs-on: ubuntu-latest
  #   steps:
  #   - name: start_jetstream
  #     run: |
  #       chmod a+x ${{ github.workspace }}/.github/workflows/entrypoint.sh
  #       docker cp ${{ github.workspace }}/.github/workflows/entrypoint.sh jetstream:/usr/local/bin/docker-entrypoint.sh
  #       docker restart jetstream
  
  # install_nats_manually:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: nats:latest
  #     ports:
  #       - 4222:4222
  #       - 8222:8222
  #     steps:
  #       name: start nats server
  #       run: --js
  # test_connection:
  #   runs-on: ubuntu-latest
  #     steps:
  #       name: http to nats
  #       run: curl http://localhost:8222/jsz
