on:
  - pull_request
  - push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: nats:alpine
      ports:
        - 4222:4222
        - 8222:8222
    steps:
        #  - name: add bash
        #    run: apk add bash bash-doc bash-completion
         - name: start jetstream
           run: /usr/local/bin/nats-server --js
  # install_nats_manually:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: nats:latest
  #     ports:
  #       - 4222:4222
  #       - 8222:8222
  #     steps:
  #       name: start nats server
  #       run: --js
  # test_connection:
  #   runs-on: ubuntu-latest
  #     steps:
  #       name: http to nats
  #       run: curl http://localhost:8222/jsz
