on:
  - pull_request
  - push

name: create_and_delete
jobs:
  test_create_and_delete:
    runs-on: ubuntu-latest
    services:
      jetstream:
        image: nats
        ports:
          - 4222:4222
          - 8222:8222
        options: --name jetstream
    steps:
      - uses: actions/checkout@v3

      - name: start_jetstream
        run: |
          chmod a+x ${{ github.workspace }}/.github/workflows/entrypoint.sh
          docker cp ${{ github.workspace }}/.github/workflows/entrypoint.sh jetstream:/usr/local/bin/docker-entrypoint.sh
          docker restart jetstream

      # - name: Sleep for 30 seconds
      #   uses: whatnick/wait-action@master
      #   with:
      #     time: '30s'
      - name: http to nats
        run: curl https://localhost:8222/jsz

# jobs:
#   set_up_nats:
#     name: set up nats
#     runs-on: ubuntu-latest
#     container:
#       image: nats:alpine
#       ports:
#         - 4222:4222
#         - 8222:8222
#       options: --name jetstream
#     steps:
#     - uses: actions/checkout@v3
#     - name: start_jetstream
#       run: |
#         chmod a+x ${{ github.workspace }}/.github/workflows/entrypoint.sh
#         docker cp ${{ github.workspace }}/.github/workflows/entrypoint.sh jetstream:/usr/local/bin/docker-entrypoint.sh
#         docker restart jetstream

    #      - name: start jetstream
    #        run: /usr/local/bin/nats-server --js
  # start_nats_instance:
  #   #  runs-on: ubuntu-latest
  #   steps:
  #   - name: start_jetstream
  #     run: |
  #       chmod a+x ${{ github.workspace }}/.github/workflows/entrypoint.sh
  #       docker cp ${{ github.workspace }}/.github/workflows/entrypoint.sh jetstream:/usr/local/bin/docker-entrypoint.sh
  #       docker restart jetstream
  
  # install_nats_manually:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: nats:latest
  #     ports:
  #       - 4222:4222
  #       - 8222:8222
  #     steps:
  #       name: start nats server
  #       run: --js
  # test_connection:
  #   runs-on: ubuntu-latest
  #     steps:
  #       name: http to nats
  #       run: curl http://localhost:8222/jsz
